version: '2.3'
services:
  kaggle:
    image: gcr.io/kaggle-gpu-images/python
    runtime: nvidia
    container_name: kaggle
    user: root
    ports:
      - "8888:8888"
    volumes:
      - ..:/notebooks
    command: >
      bash -c "
      export LD_LIBRARY_PATH=/usr/local/cuda/lib64 &&
      conda install jupyterlab &&
      pip install tornado==4.5.3 &&
      pip install jupyter_contrib_nbextensions &&
      pip install jupyter_nbextensions_configurator &&
      jupyter contrib nbextension install --user &&
      jupyter nbextension enable toc2/main --user &&
      jupyter notebook --notebook-dir=/notebooks --ip='*' --port=8888 --no-browser --allow-root --NotebookApp.token=''
      "
